const archive=window.HOT_ARCHIVE;const creatorArchive=window.CREATOR_WATCHLIST||{platforms:{douyin:[],channels:[],podcasts:[],people:[]},priorityGuests:[],totals:{records:0,uniqueNames:0}};const $=s=>document.querySelector(s);const fmt=n=>Number(n||0).toLocaleString('zh-CN');
let active='全部';let activeView='topics';let creatorPlatform='全部';let dates=Object.keys(archive.days).sort().reverse();let selectedDate=dates[0];
const creatorRecords=[...(creatorArchive.platforms.douyin||[]).map(name=>({name,platform:'抖音'})),...(creatorArchive.platforms.channels||[]).map(name=>({name,platform:'视频号'})),...(creatorArchive.platforms.podcasts||[]).map(item=>({...item,platform:'海外播客/访谈'})),...(creatorArchive.platforms.people||[]).map(item=>({...item,platform:'海外人物'}))];
function creatorKey(name){return String(name||'').replace(/（截图[^）]*）/g,'').replace(/[\s.·—_\-]/g,'').toLowerCase()}
const creatorKeys=new Set(creatorRecords.map(item=>creatorKey(item.name)));
function isWatchedCreator(name){return creatorKeys.has(creatorKey(name))}
const current=()=>archive.days[selectedDate];
function prettyDate(date){const [y,m,d]=date.split('-');return `${y}年${m}月${d}日`}
function renderDates(){
  $('#dateSelect').innerHTML=dates.map(d=>`<option value="${d}" ${d===selectedDate?'selected':''}>${prettyDate(d)}${d===dates[0]?' · 最新':''}</option>`).join('');
  $('#dateLabel').textContent=prettyDate(selectedDate);const index=dates.indexOf(selectedDate);
  $('#prevDate').disabled=index===dates.length-1;$('#nextDate').disabled=index===0;
}
function renderStats(){const topics=current().topics;const videoCount=topics.reduce((n,x)=>n+(x.videos?.length||0),0);const cats=new Set(topics.map(x=>x.cat)).size;$('#stats').innerHTML=[['当日选题',topics.length,'完整归档'],['爆款视频',videoCount,'可直达原视频'],['重点账号',creatorArchive.totals.records||creatorRecords.length,'抖音与视频号'],['覆盖板块',cats,'分类筛选'],['历史日期',dates.length,'持续累积']].map(x=>`<div class="stat"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-trend">● ${x[2]}</div></div>`).join('')}
function renderTabs(){const cats=['全部','财经','科技','社会','国际时政'];$('#tabs').innerHTML=cats.map(x=>`<button class="tab ${x===active?'active':''}" data-cat="${x}">${x}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderTabs();renderCards()})}
const metricLabels={views:'播放',likes:'点赞',favorites:'收藏',comments:'评论',shares:'转发'};
function metricValue(value,v){return value===null||value===undefined||value===''?(v?.status?.includes('未公开')?'未公开':'待核验'):value}
function platformName(v){if(v.platform)return v.platform;const u=v.url||'';if(u.includes('douyin.com'))return '抖音';if(u.includes('xiaohongshu.com'))return '小红书';if(u.includes('channels.weixin.qq.com'))return '视频号';if(u.includes('bilibili.com'))return '哔哩哔哩';if(u.includes('kuaishou.com'))return '快手';if(u.includes('weibo.com'))return '微博';if(u.includes('youtube.com')||u.includes('youtu.be'))return 'YouTube';return '其他平台'}
function copyLinkButton(url,label){return `<button class="copy-link-btn" type="button" data-copy-url="${encodeURIComponent(url)}" data-copy-kind="${label}" aria-label="复制${label}链接">复制链接</button>`}
function videoBlock(v,x){const metrics=v.metrics||{};const watched=isWatchedCreator(v.creator);return `<div class="video ${watched?'watched-video':''}"><a class="video-lead" href="${v.url}" target="_blank" rel="noopener"><div class="play">▶</div><div class="video-main"><strong>${v.title}</strong><span><em class="platform-badge">${platformName(v)}</em>${watched?'<em class="watch-badge">重点博主</em>':''}${v.creator} · ${v.duration}</span><span>采集 ${v.captured} · ${v.status||'数据待核验'}</span></div></a><div class="video-metrics">${Object.entries(metricLabels).map(([key,label])=>{const value=metricValue(metrics[key],v);return `<div class="video-metric ${value==='待核验'||value==='未公开'?'pending':''}"><b>${value}</b><span>${label}</span></div>`}).join('')}</div><div class="video-actions"><div class="link-actions"><a class="video-link" href="${v.url}" target="_blank" rel="noopener">原视频 ↗</a>${copyLinkButton(v.url,'视频')}</div><button class="analyze-btn" data-topic="${encodeURIComponent(x.title)}" data-video="${encodeURIComponent(v.url)}">分析并生成文案</button></div></div>`}
function renderCards(){const q=$('#search').value.trim().toLowerCase();const ranked=[...current().topics].sort((a,b)=>b.score-a.score);const rankOf=x=>ranked.indexOf(x)+1;const rows=ranked.filter(x=>(active==='全部'||x.cat===active)&&(!q||(`${x.title}${x.hook}${x.platform}${(x.videos||[]).map(v=>v.creator+v.title).join('')}`).toLowerCase().includes(q)));$('#topicGrid').innerHTML=rows.map(x=>{const ai=x.cat==='科技'&&/AI|人工智能|大模型|GPT|OpenAI|算力|芯片|机器人|智能体|具身|自动驾驶|Cybercab|Robotaxi|数据中心/i.test(`${x.title}${x.hook}`);return `<article class="card"><div class="card-head"><div class="head-left"><span class="rank rank-${Math.min(rankOf(x),3)}">当日第 ${rankOf(x)} 名</span><span class="tag ${x.cat}">${x.cat}</span>${ai?'<span class="ai-focus">AI重点</span>':''}</div><span class="score">热力值 ${fmt(x.score)}</span></div><h2>${x.title}</h2><p class="hook">${x.hook}</p><div class="meta"><span class="pill">${x.platform}</span>${x.source?`<span class="source-actions"><a class="pill source" href="${x.source}" target="_blank" rel="noopener">新闻来源 ↗</a>${copyLinkButton(x.source,'文章')}</span>`:''}<span class="pill ${x.videos?.length?'ok':'warn'}">${x.videos?.length?`${x.videos.length} 条视频已附链接`:'视频数据待补充'}</span></div>${x.videos?.length?`<div class="videos">${x.videos.map(v=>videoBlock(v,x)).join('')}</div>`:`<div class="empty-video">当前公开页面未提供可核验的视频直链与互动数据</div>`}</article>`}).join('')||'<div class="card empty"><h2>没有匹配结果</h2><p class="hook">换一个关键词、日期或分类试试。</p></div>'}

function renderCreatorTabs(){const tabs=['全部','抖音','视频号','海外播客/访谈','海外人物'];$('#creatorTabs').innerHTML=tabs.map(platform=>`<button class="creator-tab ${platform===creatorPlatform?'active':''}" type="button" data-platform="${platform}">${platform}${platform==='全部'?` ${creatorRecords.length}`:` ${creatorRecords.filter(item=>item.platform===platform).length}`}</button>`).join('')}
function renderCreatorCards(){const q=$('#creatorSearch').value.trim().toLowerCase();const rows=creatorRecords.filter(item=>(creatorPlatform==='全部'||item.platform===creatorPlatform)&&(!q||`${item.name}${item.type||''}${item.focus||''}`.toLowerCase().includes(q)));$('#creatorGrid').innerHTML=rows.map(item=>{const needsReview=item.name.includes('待复核');const displayName=item.name.replace(/（截图[^）]*）/g,'');const overseas=item.platform==='海外播客/访谈'||item.platform==='海外人物';const linkKind=item.platform==='海外人物'?'人物':'播客';return `<article class="creator-card ${overseas?'podcast-card':''}"><div class="creator-avatar" aria-hidden="true">${safeText(displayName.slice(0,1))}</div><div class="creator-main"><h3>${safeText(displayName)}</h3>${overseas?`<div class="podcast-focus">${safeText(item.focus)}</div>`:''}<p><span class="creator-platform ${item.platform==='抖音'?'douyin':item.platform==='视频号'?'channels':item.platform==='海外人物'?'person':'podcast'}">${item.platform}</span>${overseas?`<span class="monitor-badge">${safeText(item.type)}</span>`:needsReview?'<span class="review-badge">名称待复核</span>':'<span class="monitor-badge">每日监测</span>'}</p></div><div class="creator-actions">${item.url?`<a class="creator-open" href="${item.url}" target="_blank" rel="noopener">官网 ↗</a>${copyLinkButton(item.url,linkKind)}`:`<button class="copy-name-btn" type="button" data-copy-name="${encodeURIComponent(displayName)}" aria-label="复制博主名称">复制名称</button>`}</div></article>`}).join('')||'<div class="creator-empty">没有匹配的重点信源。</div>'}
function renderCreatorView(){renderCreatorTabs();renderCreatorCards();$('#creatorCount').textContent=creatorRecords.length;$('#creatorSummary').textContent=`抖音 ${creatorArchive.platforms.douyin.length} 个、视频号 ${creatorArchive.platforms.channels.length} 个账号、海外播客与访谈 ${creatorArchive.platforms.podcasts.length} 档、海外重点人物 ${creatorArchive.platforms.people.length} 位；优先追踪 AI 相关对话。`}
function switchView(view){activeView=view;document.querySelectorAll('.view-btn').forEach(button=>button.classList.toggle('active',button.dataset.view===view));$('#topicToolbar').hidden=view!=='topics';$('#topicGrid').hidden=view!=='topics';$('#creatorPanel').hidden=view!=='creators'}

const audienceMap={财经:['投资者','创业者','企业经营者','普通家庭'],科技:['AI行业从业者','创业者','投资人','普通人'],社会:['普通家庭','行业从业者','政策关注者','内容创作者'],国际时政:['投资者','外贸与企业经营者','国际新闻受众','普通人']};
let analysisContext=null;let currentScript='';
function safeText(s){return String(s||'').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}
function audienceProblem(cat,audience){const map={投资者:'判断事件会影响哪些资产、行业和风险定价',创业者:'找到政策或技术变化中的新需求与商业机会',企业经营者:'判断成本、订单、供应链和经营策略会怎样变化','AI行业从业者':'判断技术趋势会淘汰什么能力、放大什么能力',普通家庭:'把宏观变化翻译成收入、消费和资产决策',普通人:'理解这件事与工作、收入和生活成本有什么关系',行业从业者:'看清行业规则变化以及职业机会与风险',政策关注者:'理解政策为什么出台、影响谁以及执行边界',内容创作者:'找到大众最关心的冲突、疑问和传播切口','外贸与企业经营者':'判断汇率、能源、订单和供应链风险','国际新闻受众':'理解各方利益、事件演变与中国视角'};return map[audience]||'理解事件与自身决策的关系'}
function buildScript(topic,v,audience,targetChars,opinion){const ai=/AI|人工智能|算力|模型|芯片/i.test(`${topic.title}${topic.hook}${v.title}`);const core=`${topic.hook.replace(/[？?]$/,'')}`;const personal=opinion?`\n\n我更想提醒你的是：${opinion.replace(/[。！？!?]+$/,'')}。`:'';const red=ai?'\n\n想抓住AI时代的颠覆性红利，别只追最热的名字，要看谁能把技术真正变成客户愿意付钱的结果。':'';const close=ai?'我是李菲特，带你抓住AI时代的颠覆性红利，看懂科技背后的商业逻辑。':'我是李菲特，带你把热点看成判断，把信息变成决策。';let body=`${v.title}。\n\n很多人看到这条消息，只会停在热闹上。\n\n但真正值得关注的，是${core}。\n\n我是李菲特，做了14年科技投资。\n\n这件事表面上讲的是“${topic.title}”，背后其实有三层变化。\n\n第一，旧规则正在失效，过去习以为常的成本、优势和判断方法，需要重新计算。\n\n第二，资源会流向更有效率、更接近真实需求的人。谁能解决具体问题，谁才更有定价权。\n\n第三，它最终会落到每个人身上：你的工作会不会变化，你的钱该放在哪里，你现在积累的能力还能不能继续值钱。\n\n如果你是${audience}，最该问的不是“这条视频火不火”，而是：它会改变谁的利益？机会落在哪一层？风险最后由谁承担？${personal}${red}\n\n所以看热点，不能只记住一个结论。要顺着利益链往下看，找到与你最相关的那一环。`;
const verify=`\n\n再往深一层看，这条内容仍有三个问题需要核实。第一，数据的统计口径是什么；第二，短期热度能不能变成长期趋势；第三，作者的推演与已经发生的事实有没有混在一起。真正有价值的文案，不是照搬爆款观点，而是在保留传播力的同时，把事实、判断和个人观点分开。`;
const chain=`\n\n接下来顺着利益链看。任何热点都不是凭空发生的：上游提供资源和基础设施，中游负责组织与放大，下游把变化变成产品、服务和用户体验。越接近最终用户，越要回答一个现实问题——观众为什么愿意付钱，企业为什么愿意改变，普通人为什么必须在意。只有找到这条链里最稀缺、最难替代的一环，才能判断热度最后会沉淀成谁的收入和利润。`;
const risk=`\n\n当然，趋势成立不代表所有参与者都会受益。价格上涨可能伴随成本上升，用户增长可能掩盖获客困难，政策支持也不等于商业模式自动成立。判断机会时至少要看四件事：需求是否真实、现金流能否持续、竞争者能否快速复制、最坏情况下谁承担损失。把这四个问题想清楚，才能避免把行业红利误当成某一家公司的确定性。`;
const action=`\n\n最后说说怎么行动。对${audience}来说，第一步不是立刻下注，而是建立观察清单：持续跟踪关键数据、头部公司的真实收入、用户是否重复付费，以及政策落地后的实际效果。第二步是做小规模验证，用最低成本测试自己的判断。第三步才是扩大投入。热点提供的是线索，不是答案；真正的优势来自比别人更早验证，也比别人更快承认自己看错。`;
const counter=`\n\n我们还要做一次反向推演。如果这条热门观点是错的，最可能错在哪里？可能是样本太少，也可能是把相关性当成因果，还可能是忽略了监管、成本和用户习惯。把反方观点放进文案，不会削弱立场，反而会让判断更可信。因为成熟的观点不是只会证明自己正确，而是知道在什么条件下需要修正。`;
body+=verify;if(Number(targetChars)>=1600)body+=chain+risk;if(Number(targetChars)>=1800)body+=action+counter;
const minChars=Number(targetChars)===1600?1401:Number(targetChars)===1800?1601:0;
const expansions=[`\n\n把视角拉回“${topic.title}”，判断它有没有长期价值，可以观察三个信号：讨论是否从圈内扩散到大众，企业是否从试用走向持续付费，以及政策与基础设施是否开始配套。三个信号同时出现，热点才更可能成为趋势。`,`\n\n对${audience}而言，还要区分“知道”和“做到”。知道一条消息并不会自动产生收益，只有把信息转化成观察指标、行动顺序和退出条件，才算形成决策。先写下什么证据会证明判断成立，再写下什么变化出现时必须止损。`,`\n\n传播层面也一样。爆款视频通常把复杂问题压缩成一个鲜明结论，但我们在口播里必须补回关键前提：时间范围、适用对象和数据来源。这样既保留观点的冲击力，也不会为了流量牺牲可信度。`,`\n\n如果继续追踪这件事，下一步应关注真实用户反馈、产业链订单变化、头部参与者的投入节奏，以及竞争者有没有快速跟进。与其每天追逐新名词，不如围绕这些变量建立连续记录，趋势会在数据里逐渐显形。`,`\n\n最后再回到普通人的选择。面对快速变化，最稳妥的方法不是押中每一次风口，而是提高自己的适应速度：保留现金流，积累可迁移能力，接触真实客户，同时给新机会设置小成本试错窗口。`,`\n\n还有一个容易被忽略的变量，就是节奏。一个方向短期爆发，可能来自情绪、补贴或集中曝光；真正能持续的增长，必须经得住用户留存、复购和现金流检验。观察半年后的数据，往往比争论今天的口号更有价值。`,`\n\n所以这条选题最后要落到一个清晰判断：先确认事实，再拆解利益，随后观察趋势，最后才决定行动。只要其中任何一环缺少证据，就应该降低结论的确定性，并给后续变化保留修正空间。`];
let script=body;for(const paragraph of expansions){if(script.replace(/\s/g,'').length>=minChars)break;script+=paragraph}script+=`\n\n${close}`;let visible=0,result='';for(const char of script){if(!/\s/.test(char))visible++;if(visible>Number(targetChars))break;result+=char}return result}
function renderAnalysis(){const {topic,v}=analysisContext;const audience=$('#audienceSelect').value;const targetChars=$('#durationSelect').value;const wordLimitLabel=({1400:'1400字以内',1600:'1401–1600字',1800:'1601–1800字'})[targetChars];const opinion=$('#opinionInput').value.trim();const problem=audienceProblem(topic.cat,audience);const metrics=Object.entries(metricLabels).map(([k,l])=>`${l}${metricValue(v.metrics?.[k],v)}`).join('、');const questions=[`这件事与${audience}的直接关系是什么？`,`视频中的数据口径是否一致，哪些是事实、哪些是作者推演？`,`变化真正利好谁、挤压谁，持续时间有多长？`,`看完以后可以采取什么具体行动？`];currentScript=buildScript(topic,v,audience,targetChars,opinion);$('#analysisTitle').textContent=v.title;$('#analysisBasis').textContent=`分析依据：${platformName(v)}公开视频标题、选题摘要与互动数据（${metrics}）。未取得完整字幕时，不把推测当成视频原话。`;$('#analysisOutput').innerHTML=`<div class="analysis-grid"><section><h3>主题与核心内容</h3><p><b>主题：</b>${safeText(topic.title)}</p><p>${safeText(topic.hook)}</p></section><section><h3>目标受众</h3><p><b>${safeText(audience)}</b></p><p>解决的问题：${safeText(problem)}。</p></section><section><h3>爆款结构拆解</h3><ol><li>用反常识或利益冲突抓住注意力</li><li>从事件表象推进到利益链和商业逻辑</li><li>把宏观变化翻译成观众自身问题</li><li>给出可复述的判断和价值落点</li></ol></section><section><h3>观众看完会追问</h3><ol>${questions.map(q=>`<li>${safeText(q)}</li>`).join('')}</ol></section></div><section class="script-box"><h3>${wordLimitLabel}口播稿 · 当前约 ${currentScript.replace(/\s/g,'').length} 字</h3><pre>${safeText(currentScript)}</pre></section>`}
function openAnalysis(topicTitle,videoUrl){const topic=current().topics.find(t=>t.title===topicTitle);const v=topic?.videos?.find(item=>item.url===videoUrl);if(!topic||!v)return;analysisContext={topic,v};const audiences=audienceMap[topic.cat]||['普通人'];$('#audienceSelect').innerHTML=audiences.map(a=>`<option>${a}</option>`).join('');$('#opinionInput').value='';$('#analysisSource').href=v.url;$('#analysisModal').hidden=false;document.body.classList.add('modal-open');renderAnalysis()}
function closeAnalysis(){$('#analysisModal').hidden=true;document.body.classList.remove('modal-open')}
async function copyScript(){try{await navigator.clipboard.writeText(currentScript);$('#copyScript').textContent='✓ 已复制';setTimeout(()=>$('#copyScript').textContent='复制口播稿',1500)}catch{$('#copyScript').textContent='复制失败，请手动选择'}}
async function writeClipboard(text){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return}const input=document.createElement('textarea');input.value=text;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();const copied=document.execCommand('copy');input.remove();if(!copied)throw new Error('copy failed')}
let toastTimer=null;function showCopyToast(message,isError=false){const toast=$('#copyToast');toast.textContent=message;toast.classList.toggle('error',isError);toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{toast.hidden=true},1800)}
async function copyLink(button){const original=button.textContent;try{await writeClipboard(decodeURIComponent(button.dataset.copyUrl));button.textContent='✓ 已复制';showCopyToast(`${button.dataset.copyKind}链接已复制`)}catch{button.textContent='复制失败';showCopyToast('复制失败，请打开链接后手动复制',true)}finally{setTimeout(()=>{button.textContent=original},1500)}}
function downloadScript(){const blob=new Blob([currentScript],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${analysisContext?.v.title||'口播稿'}.txt`;a.click();URL.revokeObjectURL(a.href)}
function selectDate(date){selectedDate=date;active='全部';renderDates();renderStats();renderTabs();renderCards()}
function init(){
  $('#updateTime').textContent=`数据更新 ${archive.updated}`;document.querySelector('footer').textContent=`${archive.methodology||''} 播放、点赞、收藏、评论、转发均按平台公开口径独立采集；未公开项目明确标注，不猜测。`;renderDates();renderStats();renderTabs();renderCards();renderCreatorView();switchView(activeView);
  $('#search').oninput=renderCards;$('#dateSelect').onchange=e=>selectDate(e.target.value);
  document.querySelectorAll('.view-btn').forEach(button=>button.onclick=()=>switchView(button.dataset.view));$('#creatorSearch').oninput=renderCreatorCards;
  $('#creatorTabs').onclick=e=>{const button=e.target.closest('.creator-tab');if(button){creatorPlatform=button.dataset.platform;renderCreatorTabs();renderCreatorCards()}};
  $('#creatorGrid').onclick=e=>{const linkButton=e.target.closest('.copy-link-btn');if(linkButton){copyLink(linkButton);return}const button=e.target.closest('.copy-name-btn');if(button){writeClipboard(decodeURIComponent(button.dataset.copyName)).then(()=>showCopyToast('博主名称已复制')).catch(()=>showCopyToast('复制失败，请手动选择',true))}};
  $('#prevDate').onclick=()=>{const i=dates.indexOf(selectedDate);if(i<dates.length-1)selectDate(dates[i+1])};
  $('#nextDate').onclick=()=>{const i=dates.indexOf(selectedDate);if(i>0)selectDate(dates[i-1])};
  $('#refreshBtn').onclick=()=>{const b=$('#refreshBtn');b.textContent='✓ 已是最新归档';setTimeout(()=>b.textContent='↻ 检查更新',1500)};
  $('#topicGrid').onclick=e=>{const copyButton=e.target.closest('.copy-link-btn');if(copyButton){copyLink(copyButton);return}const b=e.target.closest('.analyze-btn');if(b)openAnalysis(decodeURIComponent(b.dataset.topic),decodeURIComponent(b.dataset.video))};
  document.querySelectorAll('[data-close-analysis]').forEach(b=>b.onclick=closeAnalysis);$('#generateBtn').onclick=renderAnalysis;$('#copyScript').onclick=copyScript;$('#downloadScript').onclick=downloadScript;
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#analysisModal').hidden)closeAnalysis()});
}init();
