window.CREATOR_WATCHLIST={
  "updated": "2026-09-07",
  "platforms": {
    "douyin": [
      "William留学择校",
      "白话频道",
      "大威哥",
      "李菲特说",
      "李菲特—智富界",
      "小司频道",
      "董AI",
      "唐子棋",
      "财才说",
      "雪狮upup",
      "清华妈妈马兰花",
      "量见坤哥说法",
      "雪球基金",
      "Trader菲",
      "南山资本论",
      "小小鹰萱妈（截图名称后半段被截断）",
      "李小意深度观察",
      "有点在李",
      "周周认知全球",
      "树先生资产视界",
      "朱虹教授",
      "董太太",
      "周媛",
      "丸子妹",
      "直男财经",
      "小孟同志v小孟同志",
      "胡说有据",
      "大湾区老姚",
      "沈芊予",
      "天骄说",
      "哎呀朱莉娅",
      "直言财经",
      "严九元GlobalView",
      "财女小绵羊",
      "蔡公子",
      "李一舟3.0",
      "严九元资产规划",
      "韩秀云讲经济",
      "小JA学财经",
      "思进世界观",
      "笨嘴哥财经",
      "米哥聊财经",
      "资本论",
      "金融康博士",
      "温义飞财富密码",
      "冯观趋势洞察",
      "陈思讲说真话",
      "老谭说财经",
      "路口大爷",
      "天才留学生",
      "香港Jacky叔",
      "孟晓苏",
      "公信财经",
      "李俊怀聊配置",
      "香港斐姐说",
      "温义飞的急救财经",
      "温老板的香港圈",
      "小Lin说",
      "一鸣财经",
      "小狮子财经科技",
      "生哥与安迪",
      "明缘说",
      "笨鸟怎么飞",
      "十里梧桐",
      "财富论",
      "猫伊老爷",
      "德培论道（截图名称后半段被截断）",
      "阳和平说事儿",
      "发烧好了呢",
      "毒角SHOW",
      "财姐水晶",
      "财经林妹妹",
      "Mark一下-马克",
      "黄力泓讲经济趋势",
      "紫荆财富圈",
      "张涌说财经",
      "韩玮的财经世界",
      "向老师讲经济",
      "俗人六哥_AI企业智能体落地",
      "上海柳叔",
      "猴哥军情",
      "全球速探",
      "乐峥会客厅",
      "柏年说政经",
      "陈思进财富说",
      "褚说",
      "江平舟",
      "廖小爱",
      "心吾讲透价值",
      "马红漫",
      "四懂非懂",
      "麻省理工巨蟹爸",
      "龙白滔博士",
      "何毅财经课堂",
      "C位观察",
      "Harry张瀚文",
      "峰哥财富浪潮",
      "纪晓岚财经",
      "小智侃财经",
      "我的野蛮老婆",
      "付鹏的财经世界",
      "周期老宋",
      "国信财经妙先生",
      "新视野财经",
      "兔子念金🐰",
      "挣钱眼的申公豹",
      "云霄博士"
    ],
    "channels": [
      "洞察前沿-王煜全",
      "竹子爱看书",
      "王煜全-趋势洞察",
      "爽姐全球财富观",
      "彩薇姐总助小菲",
      "李菲特说",
      "李菲特-智富界AI投资创业俱乐部",
      "钱在说",
      "杨老师宏观经济",
      "S的投研观点",
      "桃宇宙",
      "小小世界芯",
      "力哥商业论",
      "老黄知识局",
      "树先生讲财经",
      "周周认知世界",
      "菠萝少年记",
      "董太太.",
      "孙万龙科技圈",
      "温姑娘资产导航",
      "范爸爸和范妈妈",
      "何亮亮瞰世界",
      "麻省理工巨蟹爸",
      "哈佛壹爸教育规划",
      "谢腾Eric",
      "雪狮upup",
      "话语爱吃碳水（截图末字待复核）",
      "娱乐婶",
      "易见Ni",
      "首席营销官",
      "哈佛老徐和AI趋势",
      "滑雪研究院",
      "混哥趋势观",
      "邓青快语",
      "老任财富故事会",
      "任泽平财富说",
      "沈芊予",
      "大湾区老姚",
      "韩玮的财经世界",
      "老罗数字财富说",
      "胡说有据Pro",
      "庄姐婚姻资产规划师",
      "常文强泰国财经",
      "凯叔有财",
      "柏年说政经",
      "李孔岳教授",
      "博雅的DEMO",
      "董舟老师来了",
      "雪球",
      "第一身份-私享会",
      "财经",
      "兔子念金",
      "汤山小王",
      "王福重来了",
      "小A学财经",
      "了不起的星总",
      "Wendy环球财富论",
      "财经1观点",
      "其钧观察",
      "笨嘴哥财经",
      "布道者赖舒然",
      "Alex包老师",
      "刘纪鹏教授",
      "小孟同志v小孟同志",
      "原子智库",
      "鸿飞说财经",
      "柳叶刀财经",
      "德龙聊经济",
      "司晨寻龙",
      "李教授讲财经",
      "严九元GlobalView",
      "Fan全球家办圈",
      "Mo姐财经",
      "谭啸讲财经",
      "陈铭全老师.",
      "昂米财经",
      "示范财经",
      "谢昊外评世界",
      "财女小绵羊同学",
      "蔡公子小哥",
      "天骄说财",
      "史大郎侃犀利",
      "野蛮老婆财经",
      "金融康博士",
      "边风炜",
      "侯总说财经",
      "瀚文价值发现",
      "珊姐说Web3",
      "飞哥说财富",
      "米哥聊财经本人",
      "王牧笛讲财富",
      "梁言良语正能量",
      "老王说房V",
      "小邵说商业",
      "泽平宏观",
      "陈思进说真话",
      "虹教授",
      "马红漫",
      "任泽平宏观",
      "硬核财经小爆姐",
      "直男财经V",
      "硬核资本论",
      "韩秀云讲经济",
      "直言财经",
      "胡晓辉深度财经",
      "咖姐的第六感财经",
      "章学财经",
      "天才留学生",
      "芝士喵M",
      "碎片里的逻辑",
      "老谋说财经",
      "香港S叔",
      "思进世界观",
      "晓芳聊财经",
      "李一舟3.0",
      "独行者李明",
      "就是酥梨",
      "财经养老万事通",
      "公信财经",
      "陈主任聊湾区",
      "孟晓苏mxs",
      "Tianya财经洞察",
      "朱国勇生意经",
      "哎呀朱莉娅",
      "路口大爷聊宏观",
      "香港Jacky叔",
      "珊言两语",
      "德龙说",
      "胡侃侃同学",
      "郭老师保险财经",
      "财经林妹妹",
      "财姐水晶说",
      "小狮子财经科技",
      "温义飞",
      "财经丸子",
      "发烧好了呢",
      "挣钱眼的申公豹",
      "李俊怀聊配置",
      "爽姐讲财",
      "笨鸟不会飞怎么飞",
      "温老板的香港圈",
      "一鸣先森",
      "小Lin说",
      "树先生认知全球",
      "桃桃房东腊月供暖一半"
    ],
    "podcasts": [
      {
        "name": "The OpenAI Podcast",
        "type": "AI深度访谈",
        "focus": "OpenAI内部、模型、产品与产业",
        "url": "https://openai.com/podcast/"
      },
      {
        "name": "No Priors",
        "type": "AI投资与创业",
        "focus": "AI研究者、创始人与投资人",
        "url": "https://podcasts.apple.com/us/podcast/no-priors-artificial-intelligence-technology-startups/id1668002688"
      },
      {
        "name": "Dwarkesh Podcast",
        "type": "AI深度访谈",
        "focus": "前沿模型、AGI、科学与社会",
        "url": "https://www.dwarkesh.com/"
      },
      {
        "name": "AI + a16z",
        "type": "硅谷风投",
        "focus": "模型、基础设施、应用与商业化",
        "url": "https://a16z.com/podcasts/ai-a16z/"
      },
      {
        "name": "The a16z Show",
        "type": "硅谷风投",
        "focus": "科技、AI、创业与产业趋势",
        "url": "https://a16z.com/podcasts/a16z-show/"
      },
      {
        "name": "The Ben & Marc Show",
        "type": "硅谷大佬对谈",
        "focus": "科技、商业、政策与AI",
        "url": "https://a16z.com/podcasts/"
      },
      {
        "name": "In the Vault",
        "type": "金融科技访谈",
        "focus": "金融服务、Fintech与AI",
        "url": "https://a16z.com/podcasts/"
      },
      {
        "name": "All-In Podcast",
        "type": "硅谷投资人圆桌",
        "focus": "科技、市场、资本与AI",
        "url": "https://allin.com/"
      },
      {
        "name": "BG2 Pod",
        "type": "科技投资",
        "focus": "科技、市场、资本主义与AI",
        "url": "https://www.bg2pod.com/"
      },
      {
        "name": "Lex Fridman Podcast",
        "type": "人物深度访谈",
        "focus": "AI、机器人、科技领袖与研究者",
        "url": "https://lexfridman.com/podcast/"
      },
      {
        "name": "Latent Space",
        "type": "AI工程",
        "focus": "智能体、模型、基础设施与AI科学",
        "url": "https://www.latent.space/podcast"
      },
      {
        "name": "The Cognitive Revolution",
        "type": "AI深度访谈",
        "focus": "AI创新者、研究与产业影响",
        "url": "https://www.cognitiverevolution.ai/"
      },
      {
        "name": "20VC",
        "type": "硅谷风投访谈",
        "focus": "VC、创始人、融资与AI公司",
        "url": "https://www.thetwentyminutevc.com/"
      },
      {
        "name": "Acquired Interviews",
        "type": "商业领袖访谈",
        "focus": "科技巨头、创始人、资本配置与AI",
        "url": "https://www.acquired.fm/features/interviews"
      },
      {
        "name": "Invest Like the Best",
        "type": "投资访谈",
        "focus": "投资人、商业模式与AI机会",
        "url": "https://colossus.com/series/invest-like-the-best/"
      },
      {
        "name": "Odd Lots",
        "type": "华尔街市场",
        "focus": "金融市场、宏观经济与AI交易",
        "url": "https://www.bloomberg.com/originals/series/odd-lots"
      },
      {
        "name": "Goldman Sachs Exchanges",
        "type": "华尔街机构",
        "focus": "全球经济、投资、AI资本开支与回报",
        "url": "https://www.goldmansachs.com/insights/podcasts/"
      },
      {
        "name": "Decoder with Nilay Patel",
        "type": "科技CEO访谈",
        "focus": "公司战略、平台权力、商业模式与AI",
        "url": "https://podcasts.apple.com/us/podcast/decoder-with-nilay-patel/id1011668648"
      },
      {
        "name": "Hard Fork",
        "type": "AI新闻与访谈",
        "focus": "AI产品、公司、监管与社会影响",
        "url": "https://www.nytimes.com/column/hard-fork"
      },
      {
        "name": "Conversations with Tyler",
        "type": "思想人物访谈",
        "focus": "经济学、科技、AI与社会",
        "url": "https://conversationswithtyler.com/"
      },
      {
        "name": "TBPN",
        "type": "科技商业直播访谈",
        "focus": "硅谷新闻、创始人、投资人与AI",
        "url": "https://www.tbpn.com/"
      },
      {
        "name": "Lenny's Podcast",
        "type": "产品与创业访谈",
        "focus": "产品、增长、AI应用与创业者",
        "url": "https://www.lennysnewsletter.com/podcast"
      },
      {
        "name": "Y Combinator",
        "type": "创业访谈",
        "focus": "AI创业、产品、融资与创始人经验",
        "url": "https://www.youtube.com/@ycombinator"
      },
      {
        "name": "Sequoia Capital",
        "type": "硅谷风投访谈",
        "focus": "AI创始人、市场判断与公司建设",
        "url": "https://www.youtube.com/@sequoiacapital"
      },
      {
        "name": "The AI Podcast by NVIDIA",
        "type": "AI产业访谈",
        "focus": "芯片、算力、机器人与AI应用",
        "url": "https://blogs.nvidia.com/ai-podcast/"
      },
      {
        "name": "SemiAnalysis Weekly",
        "type": "AI芯片与算力",
        "focus": "半导体、GPU、HBM、数据中心与模型经济",
        "url": "https://podcasts.apple.com/us/podcast/semianalysis-weekly/id1877544643"
      },
      {
        "name": "Naval Podcast",
        "type": "科技创业与思想",
        "focus": "AI、创业、财富、未来工作与社会",
        "url": "https://nav.al/"
      }
    ],
    "people": [
      {
        "name": "Gavin Baker",
        "type": "科技投资人",
        "focus": "AI投资周期、GPU、数据中心、应用软件与机器人",
        "url": "https://x.com/GavinSBaker"
      },
      {
        "name": "Dylan Patel",
        "type": "AI芯片分析师",
        "focus": "SemiAnalysis、AI算力、半导体供应链、HBM与云基础设施",
        "url": "https://semianalysis.com/dylan-patel/"
      },
      {
        "name": "Naval Ravikant",
        "type": "创业者与投资人",
        "focus": "AI、创业、财富、社会变化与长期判断",
        "url": "https://nav.al/"
      }
    ]
  },
  "priorityGuests": [
    "Sam Altman",
    "Greg Brockman",
    "Dario Amodei",
    "Demis Hassabis",
    "Jensen Huang",
    "Mark Zuckerberg",
    "Elon Musk",
    "Satya Nadella",
    "Sundar Pichai",
    "Andy Jassy",
    "Mustafa Suleyman",
    "Yann LeCun",
    "Andrej Karpathy",
    "Ilya Sutskever",
    "Mira Murati",
    "Fei-Fei Li",
    "Aravind Srinivas",
    "Alexandr Wang",
    "Arthur Mensch",
    "Gavin Baker",
    "Dylan Patel",
    "Naval Ravikant",
    "Marc Andreessen",
    "Ben Horowitz",
    "Bill Gurley",
    "Brad Gerstner",
    "Chamath Palihapitiya",
    "David Sacks",
    "Jason Calacanis",
    "David Friedberg",
    "Vinod Khosla",
    "Reid Hoffman",
    "Peter Thiel",
    "Roelof Botha",
    "Mary Meeker",
    "Cathie Wood",
    "Stanley Druckenmiller",
    "Bill Ackman",
    "Ray Dalio",
    "Ken Griffin",
    "Jamie Dimon"
  ],
  "totals": {
    "records": 282,
    "uniqueNames": 255
  }
};
